### ISSUE TITLE
IncompleteRead

### ISSUE THREAD

**Issue by hsiaoyi0504** [hsiaoyi0504/related_papers#4]
- Similar to biopython/biopython#1944.
- Suggested solution: 
  - http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc140
  - http://biopython.org/DIST/docs/tutorial/Tutorial.html#htoc141

**Comment by hsiaoyi0504** [comment]
```
Traceback (most recent call last):
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 541, in _get_chunk_left
    chunk_left = self._read_next_chunk_size()
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 508, in _read_next_chunk_size
    return int(line, 16)
ValueError: invalid literal for int() with base 16: b''

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 573, in _readinto_chunked
    chunk_left = self._get_chunk_left()
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 543, in _get_chunk_left
    raise IncompleteRead(b'')
http.client.IncompleteRead: IncompleteRead(0 bytes read)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stats.py", line 61, in <module>
    pubmed_ids = measure_annotation_time(start_date, end_date, count, webenv, query_key, MeSH_TERMS)
  File "stats.py", line 36, in measure_annotation_time
    for record in records:
  File "/home/huei820504/anaconda3/lib/python3.5/site-packages/Bio/Medline/__init__.py", line 129, in parse
    for line in handle:
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 478, in readinto
    return self._readinto_chunked(b)
  File "/home/huei820504/anaconda3/lib/python3.5/http/client.py", line 589, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(6843 bytes read)
```

**Comment by hsiaoyi0504** [comment]
```
{'VI': '9', 'EDAT': '2018/07/19 06:00', 'OTO': ['NOTNLM'], 'MHDA': '2018/07/19 06:01', 'IS': '1664-2295 (Print) 1664-2295 (Li
nking)', 'AID': ['10.3389/fneur.2018.00520 [doi]'], 'PMC': 'PMC6038713', 'AU': ['Rosazza C', 'Zaca D', 'Bruzzone MG'], 'DEP':
 '20180703', 'STAT': 'PubMed-not-MEDLINE', 'PG': '520', 'OWN': 'NLM', 'FAU': ['Rosazza, Cristina', 'Zaca, Domenico', 'Bruzzon
e, Maria G'], 'PST': 'epublish', 'DP': '2018', 'LR': '20181114', 'JID': '101546899', 'SO': 'Front Neurol. 2018 Jul 3;9:520. d
oi: 10.3389/fneur.2018.00520. eCollection 2018.', 'TA': 'Front Neurol', 'LA': ['eng'], 'AD': 'Neuroradiology Unit, Fondazione
 IRCCS Istituto Neurologico "Carlo Besta,", Milan, Italy. Center for Mind/Brain Sciences (CIMeC), University of Trento, Trent
o, Italy. Neuroradiology Unit, Fondazione IRCCS Istituto Neurologico "Carlo Besta,", Milan, Italy.', 'JT': 'Frontiers in neur
ology', 'PL': 'Switzerland', 'PHST': ['2018/02/28 00:00 [received]', '2018/06/12 00:00 [accepted]', '2018/07/19 06:00 [entrez
]', '2018/07/19 06:00 [pubmed]', '2018/07/19 06:01 [medline]'], 'PMID': '30018589', 'OT': ['functional connectivity', 'langua
ge mapping', 'motor mapping', 'preoperative setting', 'resting-state fMRI', 'task-based fMRI'], 'TI': 'Pre-surgical Brain Map
ping: To Rest or Not to Rest?', 'PT': ['Journal Article'], 'LID': '10.3389/fneur.2018.00520 [doi]', 'CRDT': ['2018/07/19 06:0
0']}
```

It seems that this record breaks current program.

**Comment by hsiaoyi0504** [comment]
Nope ... It's next record of this record....

**Comment by hsiaoyi0504** [comment]
It seems to me that this might be caused by that the number of records when you do the esearch and  the number of records when you do the efetch are different.
